### PR TITLE
Improvement: FAQ Schema - Revamped the Padding options. 

### PR DESCRIPTION
**Pull request by RajkiranBagal**
### Description
Trello task - https://trello.com/c/77TIcgei/146-faq-add-common-padding-option-for-the-whole-box-and-bottom-padding-option-for-question

### Types of changes
New feature (non-breaking change which adds functionality)

### How has this been tested?
 - Check Padding options.
 - Check Backward Compatibility 

### Checklist:
- [x] My code is tested
- [x] My code follows accessibility standards 
- [x] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [x] I've included developer documentation 
- [x] I've added proper labels to this pull request

### CODE REVIEW

**Comment by vrundakansara** [comment]
@RajkiranBagal -
Change it to -  `Gap between Q & A`
Also, remove the vertical icon - https://share.getcloudapp.com/8Lu7yG1P

**Comment by RajkiranBagal** [comment]
> @RajkiranBagal -
> Change it to - `Gap between Q & A`
> Also, remove the vertical icon - https://share.getcloudapp.com/8Lu7yG1P

@vrundakansara Ma'am Done.

**Comment by vrundakansara** [comment]
@RajkiranBagal - Handle the separator with negative margin then padding is applied - https://share.getcloudapp.com/7KumvgP9
Also place `Gap Between Q&A` below `Row Gap (px)`

**Comment by RajkiranBagal** [comment]
> @RajkiranBagal - Handle the separator with negative margin then padding is applied - https://share.getcloudapp.com/7KumvgP9
> Also place `Gap Between Q&A` below `Row Gap (px)`

Done @vrundakansara Mam

**Comment by RajkiranBagal** [comment]
Canceling this because of Backward Compatibility issues.

**Pull request closed without merging**
