### PR TITLE
Improvement: Blockquote's HTML Optimization

### PR DESCRIPTION
**Pull request by AbhijitNage123**
### Description

- Remove not-needed div and manage its CSS.
- Remove unnecessary CSS.
- Optimized style.scss.
- Doc - https://docs.google.com/document/d/1ZNsQoG4eEtac9_bxWwwt6XBkOSdfarQ3D9vaulpcss0/edit?usp=sharing

### Screenshot
- https://share.getcloudapp.com/7KuAnoKd
- https://share.getcloudapp.com/4guPWZyL

### Types of changes

- Improvement

### How has this been tested?

- Test case 1 - Backward compatibility.
- Test case 2 - Check all settings are working or not.
- Special Test case :
  - Quotes Icon normal/hover color.
  - Quote Icon Size Background size and Border Radius.
  - Quote color, Typography

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

### CODE REVIEW

**Comment by RajkiranBagal** [comment]
- Default view by just enabling Twitter icon Looks Glitchy - https://share.bsf.io/rRuWDnWy
 - We can remove this span & directly write Text - https://share.bsf.io/L1uebYWm

**Review by RajkiranBagal — CHANGES_REQUESTED** [review]
@AbhijitNage123 
 - Default view by just enabling Twitter icon Looks Glitchy - https://share.bsf.io/rRuWDnWy
 - We can remove this span & directly write Text - https://share.bsf.io/L1uebYWm
 - Do we really need all these classes? We can surely eliminate most of them - https://share.bsf.io/Z4urNz7O

**Review by RajkiranBagal — APPROVED** [review]

**Comment by akshaylakh** [comment]
1. Backward Compatibility -  On loading editor - block asked for recovery & validation error - 
2. Click on + icon to add block - console error
 Screencast for both issues -  https://share.bsf.io/2NuPOAOZ

**Comment by akshaylakh** [comment]
working fine

**Pull request merged**
