### PR TITLE
SPCTR-1132 Info Box - icon circle ratio issue, circle is not 100% round

### PR DESCRIPTION
**Pull request by sushmak02**
### Description
Infobox icon circle ratio issue, the circle is not 100% round

### Screenshots
Issue - https://brainstormforce.atlassian.net/jira/software/projects/SPCTR/boards/1?assignee=70121%3Ad8befe5d-3e2c-4e74-8556-fb11862acb20&selectedIssue=SPCTR-1132
Fixed - https://share.getcloudapp.com/P8uQGeAN

### Types of changes

Bug fix (non-breaking change which fixes an issue)

### How has this been tested?
Drag and Drop info box block

Pick an icon from the icon picker
Set Icon View as Framed and Shape as the circle
Set Icon Background Color
let’s try to make the icon 100% circle 

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

### CODE REVIEW

**Review by bsf-zanev — CHANGES_REQUESTED** [review]
The Padding Options should not be removed.
When Tested, these changes break the Style --> Icon / Image --> Padding Control when the View is set to Default.

Please make sure that this setting's functionality still remains.

**Review by AbhijitNage123 — APPROVED** [review]
LGTM

**Comment by sushmak02** [comment]
@bsf-zanev I have fixed the default icon padding issue. Please check once.

**Comment by sushmak02** [comment]
@supriyajjadhav I have fixed the image shrink issue - https://share.getcloudapp.com/NQulYPGZ
Please confirm once

**Review by bsf-zanev — APPROVED** [review]
Shrinking Image and Icon Padding Issues have been resolved.

**Pull request merged**
