### PR TITLE
Improvement: Responsive toggle component.

### PR DESCRIPTION
**Pull request by AbhijitNage123**
### Description

- https://app.startinfinity.com/b/Mi5zu3VRVzk/M7Dpq9yR4Pe/2cf84bbb-98e2-4da5-9597-d41a9e6119dd?view=6d3bcc3d-b047-4739-8e05-d9621e9f9445&t=attributes

### Types of changes

- Improvement

### How has this been tested?

- Each component should be tested 
  - Component List 
    - Multi-buttons
    - Spacing - Section
    - Range - Info-box
    - Responsive Select - Tabs
- All blocks need to be tested properly
  for e.q - for Advanced heading check Typography on responsive devices
  same for tab check the responsive spacing setting, for info-box responsive range settings like this.

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

### CODE REVIEW

**Review by RajkiranBagal — CHANGES_REQUESTED** [review]

**Review by RajkiranBagal — APPROVED** [review]

**Comment by akshaylakh** [comment]
Range control - unable to save different values on different devices-  https://share.bsf.io/6quEkvv9
Spacing - Negative margin can be passed via typing only arrow does not work -  https://share.bsf.io/llu6ZkkE

**Comment by akshaylakh** [comment]
Post grid/Carousel/Masonry/Testimonials > General > Columns - unable to save values  on devices - https://share.bsf.io/NQuxbxrQ
 Social Share > Style > Size
Lottie > Style > WIdth & Height

**Comment by akshaylakh** [comment]
@AbhijitNage123 Please check Post Grid, Carousel, Testimonial, Pricelist as discussed

**Comment by AbhijitNage123** [comment]
> @AbhijitNage123 Please check Post Grid, Carousel, Testimonial, Pricelist as discussed

Fixed. Post grid and Price-List working fine

**Comment by akshaylakh** [comment]
working fine

**Pull request merged**
