### PR TITLE
Fix: Masonry Feature - Broken with new core/gallery.

### PR DESCRIPTION
**Pull request by AbhijitNage123**
### Description

- Task - https://app.startinfinity.com/b/Mi5zu3VRVzk/M7Dpq9yR4Pe/f8588fc4-5f3a-4254-bab2-575c9fd9b467?view=6d3bcc3d-b047-4739-8e05-d9621e9f9445&t=attributes

### Types of changes

- Breaking change 

### How has this been tested?

- Backword - creates masonry using core/gallery in master and then switch to `next-release`.
- Install Gutenberg plugin.
- Drag and drop core/gallery add images
- Check Masonry tab is visible or not.
- Switch to `masonry-feature-broken-with-new-core-gallery`  and check by enabling the masonry feature.

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

### CODE REVIEW

**Review by RajkiranBagal — APPROVED** [review]

**Comment by akshaylakh** [comment]
Backward Compatibility - https://share.bsf.io/KouYGOL2
Gap not working on front end

**Comment by akshaylakh** [comment]
> Backward Compatibility - https://share.bsf.io/KouYGOL2 Gap not working on front end

@AbhijitNage123 Backward Compatibility issue is still pending, getting value undefined

**Comment by akshaylakh** [comment]
- Switch to this branch, don't activate GB plugin - gap not applicable
- Activate GB plugin, on front end Margin bottom applies, not left right

**Comment by akshaylakh** [comment]
working fine

**Comment by AbhijitNage123** [comment]
@akshaylakh Gutenberg team fix this issue there end. Please test it once by cloning Gutenberg at your end and switching specific branch. issue reported [here](https://github.com/WordPress/gutenberg/issues/37675) solution mention [here](https://github.com/WordPress/gutenberg/pull/37812)

**Comment by akshaylakh** [comment]
working fine

**Comment by glendaviesnz** [comment]
@AbhijitNage123, @akshaylakh I just changed the approach for the fix in https://github.com/WordPress/gutenberg/pull/37812 to make it more standard with the way other blocks handle the passing through of attributes in the migrations. It should still work as expected, but you may want to retest it.

**Comment by AbhijitNage123** [comment]
Thanks, @glendaviesnz, Yes tested working fine as expected.

**Comment by akshaylakh** [comment]
Working fine in the new method too. Thanks @glendaviesnz

**Review by sandeshjangam — APPROVED** [review]

**Pull request merged**
