### PR TITLE
Improvement: Taxonomy HTML Optimization

### PR DESCRIPTION
**Pull request by AbhijitNage123**
### Description

- Removed `uagb-taxonomy-wrap` div and added dynamic class to the main wrap.
- Removed `uagb-tax-separator-wrap` div

### Types of changes

- Improvement

### How has this been tested?

- All settings option.
- Backword testing.

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [] I've included developer documentation 
- [x] I've added proper labels to this pull request

### CODE REVIEW

**Review by RajkiranBagal — CHANGES_REQUESTED** [review]
- Remove Count Number Span/Div
 -

**Comment by AbhijitNage123** [comment]
> * Remove Count Number Span/Div

Removed. Please review

**Comment by akshaylakh** [comment]
@AbhijitNage123 Typography is not working in Grid & List layout on front end -

**Comment by AbhijitNage123** [comment]
@akshaylakh Resolve please check.

**Comment by akshaylakh** [comment]
working fine

**Review by sandeshjangam — APPROVED** [review]

**Pull request merged**
