### PR TITLE
refactor: Post Grid, Masonry & Carousel Block's HTML, Classes & CSS.

### PR DESCRIPTION
**Pull request by RajkiranBagal**
### Description
 - Report - https://docs.google.com/document/d/1eUpPlpSKIiUKbQkx19kcSDziDO_h4VYxv9D6pb3wTRU/edit?usp=sharing

### Types of changes
Bug fix (non-breaking change which fixes an issue)

### How has this been tested?
 - Test whole functionality.
 - Test Backward Compatibility.
 - Test Carousel & Masonry.

### Checklist:
- [x] My code is tested
- [x] I've included any necessary tests 
- [x] I've added proper labels to this pull request

### CODE REVIEW

**Comment by AbhijitNage123** [comment]
Layout break on frontend - https://share.getcloudapp.com/04u5jJ8y (Clear cache, delete custom-style-css file, regenerate assets )

**Comment by RajkiranBagal** [comment]
> Layout break on frontend - https://share.getcloudapp.com/04u5jJ8y (Clear cache, delete custom-style-css file, regenerate assets )

Not able to reproduce, Please share steps.

**Comment by AbhijitNage123** [comment]
@RajkiranBagal 
- Equal height was not working. See here - https://share.getcloudapp.com/mXuPLpex
- Read more bg color not working frontend as well as on backend - https://share.getcloudapp.com/2NuPLwg6
- Alignment issue - https://share.getcloudapp.com/bLudnkzK

**Comment by RajkiranBagal** [comment]
> @RajkiranBagal
> 
> * Equal height was not working. See here - https://share.getcloudapp.com/mXuPLpex
> * Read more bg color not working frontend as well as on backend - https://share.getcloudapp.com/2NuPLwg6
> * Alignment issue - https://share.getcloudapp.com/bLudnkzK

Fixed!

**Comment by AbhijitNage123** [comment]
Read more button bg color - https://share.getcloudapp.com/Z4urgJWX
Masonry pagination load more button not visible when pagination is ON - https://share.getcloudapp.com/v1ujXlZ9
Masonry pagination scroll giving issue on frontend - https://share.getcloudapp.com/6quvykqK

**Comment by RajkiranBagal** [comment]
> Read more button bg color - https://share.getcloudapp.com/Z4urgJWX Masonry pagination load more button not visible when pagination is ON - https://share.getcloudapp.com/v1ujXlZ9 Masonry pagination scroll giving issue on frontend - https://share.getcloudapp.com/6quvykqK

Fixed!

**Review by AbhijitNage123 — APPROVED** [review]
Look good to me.

**Comment by akshaylakh** [comment]
Backward Compatibility > Pagination - styling not working in editor  - https://share.bsf.io/5zu9Qok2
Backward Compatibility> Content Padding not applying on front end in editor  -  https://share.bsf.io/Wnuko5Bk
Uncaught promise in console -  https://share.bsf.io/Z4urOEro
Read More link hover color not working - https://share.bsf.io/2NuPnQmZ

**Comment by akshaylakh** [comment]
Post Carousel 
Read more > Hover color not working https://share.bsf.io/E0uKxBAr

**Comment by akshaylakh** [comment]
Post Masonry 
Read More - Hover color not working 
Posts position changed -  https://share.bsf.io/mXuPwOnx (please confirm)

**Comment by RajkiranBagal** [comment]
@akshaylakh Issues fixed, Please test.

**Comment by akshaylakh** [comment]
> Post Grid Backward Compatibility > Pagination - styling not working in editor - https://share.bsf.io/5zu9Qok2 Backward Compatibility> Content Padding not applying on front end in editor - https://share.bsf.io/Wnuko5Bk Uncaught promise in console - https://share.bsf.io/Z4urOEro Read More link hover color not working - https://share.bsf.io/2NuPnQmZ

Content padding - Top , bottom not working on front end

**Comment by akshaylakh** [comment]
> Post Carousel Read more > Hover color not working https://share.bsf.io/E0uKxBAr

not working on front end

**Comment by akshaylakh** [comment]
> Posts position changed - https://share.bsf.io/mXuPwOnx (please confirm)

Position changed issue present

**Comment by akshaylakh** [comment]
> > Post Grid Backward Compatibility > Pagination - styling not working in editor - https://share.bsf.io/5zu9Qok2 Backward Compatibility> Content Padding not applying on front end in editor - https://share.bsf.io/Wnuko5Bk Uncaught promise in console - https://share.bsf.io/Z4urOEro Read More link hover color not working - https://share.bsf.io/2NuPnQmZ
> 
> Content padding - Top , bottom not working on front end

fixed

**Comment by akshaylakh** [comment]
> > Post Carousel Read more > Hover color not working https://share.bsf.io/E0uKxBAr
> 
> not working on front end

fixed

**Comment by akshaylakh** [comment]
> Post Masonry Read More - Hover color not working Posts position changed - https://share.bsf.io/mXuPwOnx (please confirm)

fixed

**Review by sandeshjangam — APPROVED** [review]

**Review by sandeshjangam — APPROVED** [review]

**Pull request merged**
