### PR TITLE
Fix: Backward compatibility issues in all block due to svg URL change

### PR DESCRIPTION
**Pull request by supriyajjadhav**
### Description
Fixed backward compatibility issues for all blocks

### Types of changes
non-breaking change 

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

### CODE REVIEW

**Comment by AbhijitNage123** [comment]
@supriyajjadhav Added deprecated render Icon js file. Now use it in deprecated files or deprecated components where it is needed.

**Comment by AbhijitNage123** [comment]
Tested and fixed some issues in the Advanced column, Multi buttons, WP Search and Review Schema. Working Fine now.

**Review by RajkiranBagal — APPROVED** [review]

**Comment by akshaylakh** [comment]
Console errors - https://share.bsf.io/6quEPWdw

**Comment by akshaylakh** [comment]
> Console errors - https://share.bsf.io/6quEPWdw
> Advance Column seems a bit shorter in editor - https://share.bsf.io/8LupryGe

Added issues -  [link 1 ](https://app.startinfinity.com/b/Mi5zu3VRVzk/3sAgbH1y7qY/a16fa07a-71df-4dfc-b4e6-145b40adf61c?view=6e170ea7-8708-4546-8b82-23d2eebdf694&t=attributes&redirect=true)

**Review by sandeshjangam — APPROVED** [review]

**Pull request merged**
