### PR TITLE
Integration with Toolset Dynamic Sources

### PR DESCRIPTION
**Pull request by kmgalanakis**
In this PR I'm integrating the [Toolset Dynamic Sources library](https://github.com/OnTheGoSystems/toolset-dynamic-sources) into three of your blocks:
* Advanced heading (Heading text & Description)
* Blockquote (Quote text & Author)
* Section (Dynamic image for the section background when image background is selected)

Please disregard the code changes in `classes/class-uagb-helper.php` as these changes were needed on your codebase in order to make the template styling thing work for the demo but I'm sure we can find a better way to achieve the desired outcome by using maybe a hook in your codebase. We can collaborate on this.

I am at your disposal if you have questions or suggestions.

### CODE REVIEW

**Comment by vrundakansara** [comment]
Hey @kmgalanakis ,
We will be adding the XML file in the upcoming update. I am closing the PR.

Thank you for your cooperation.

Regards,
Vrunda Kansara

**Comment by kmgalanakis** [comment]
@vrundakansara I'm sorry but I'm not following? For which XML are you talking about?

**Comment by vrundakansara** [comment]
Hey @kmgalanakis ,

One of your colleagues shared this file with us - https://github.com/brainstormforce/ultimate-addons-for-gutenberg/blob/wpml-compatibility/wpml-config.xml

We will be adding this file in our next update.

**Comment by kmgalanakis** [comment]
@vrundakansara this has to do with WPML compatibility. It's irrelevant to the work done in this PR.

**Comment by vrundakansara** [comment]
Indeed @kmgalanakis .

**Pull request closed without merging**
