### PR TITLE
Improvement: increase number of child block in social share

### PR DESCRIPTION
**Pull request by supriyajjadhav**
### Description
increase number of child block in social share

### Types of changes
non-breaking change 

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

### CODE REVIEW

**Review by RajkiranBagal — APPROVED** [review]

**Comment by akshaylakh** [comment]
Child block validation error -  https://share.bsf.io/E0uo4W2A
Can we use three different type of icons-  Facebook, Twitter, Linkedin

**Comment by AbhijitNage123** [comment]
> Child block validation error - https://share.bsf.io/E0uo4W2A Can we use three different type of icons- Facebook, Twitter, Linkedin

@akshaylakh Please test once the validation issue is fixed. diff icon on drag and drop - Facebook, Pinterest, and Twitter

**Comment by akshaylakh** [comment]
> @akshaylakh Please test once the validation issue is fixed. diff icon on drag and drop - Facebook, Pinterest, and Twitter

Validation error is present, please check with shared HTML.

**Comment by akshaylakh** [comment]
working fine

**Review by sandeshjangam — APPROVED** [review]

**Pull request merged**
